# Generated by Django 2.0.6 on 2018-06-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosdvlpr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
