# Generated by Django 2.0.6 on 2018-06-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosdvlpr', '0002_comment_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='thread',
            name='framework',
            field=models.ManyToManyField(to='sosdvlpr.Language'),
        ),
    ]
